clone:
      tags: true

build:
  bundle:
    image: dock.pw.fr/pw/debpkg:$$DEBIAN_VERSION
    commands:
      - echo "deb http://ftp.fr.debian.org/debian/ jessie-backports main" > /etc/apt/sources.list.d/backports.list
      - apt-get update >/dev/null
      - apt-get install -y -t jessie-backports cmake libhiredis-dev libhiredis-dbg valgrind
      - make
      - make test
      - valgrind ./test
      - debuild -uc -b
publish:
  sftp:
    host: pippin.planet-work.net
    username: pkg
    files:
      - ../*.deb
    destination_path: incoming/libnss-redis/$$DEBIAN_VERSION
    when:
      event: tag
  ssh:
    host: pippin.planet-work.net
    user: pkg
    commands:
      - aptly repo add debian-$$DEBIAN_VERSION incoming/libnss-redis/$$DEBIAN_VERSION && aptly publish update $$DEBIAN_VERSION debian 
    when:
      event: tag

matrix:
  DEBIAN_VERSION:
    - jessie

