pipeline:
  clone:
    image: plugins/git
    tags: true

  build:
    image: dock.pw.fr/pw/debpkg:jessie
    commands:
      - echo "deb http://ftp.fr.debian.org/debian/ jessie-backports main" > /etc/apt/sources.list.d/backports.list
      - apt-get update >/dev/null
      - apt-get install -y -t jessie-backports cmake libhiredis-dev libhiredis-dbg valgrind
      - make
      - make test
      - valgrind ./test
      - debuild -uc -b

  pkg:
    image: appleboy/drone-scp
    host: pippin.planet-work.net
    username: pkg
    source: ../*.deb
    target: incoming/libnss-redis/jessie
    when:
        event: tag

  aptly:
    image: appleboy/drone-ssh
    host: pippin.planet-work.net
    user: pkg
    script:
      - aptly repo add debian-jessie incoming/libnss-redis/jessie && aptly publish update jessie debian 
    when:
      event: tag

matrix:
  DEBIAN_VERSION:
    - jessie

