pipeline:
  build:
    image: dock.pw.fr/pw/debpkg:${DEBIAN_VERSION}
    commands:
      - echo "deb http://ftp.fr.debian.org/debian/ ${DEBIAN_VERSION}-backports main" > /etc/apt/sources.list.d/backports.list
      - apt-get update >/dev/null
      - '[ "${DEBIAN_VERSION}" = "stretch" ] && apt-get install -y cmake libhiredis-dev libhiredis-dbg valgrind redis-server clang || apt-get install -y -t ${DEBIAN_VERSION}-backports cmake libhiredis-dev libhiredis-dbg valgrind redis-server clang'
      - sed -i -e "s/6379/6380/" /etc/redis/redis.conf
      - echo "unixsocket /var/run/redis/redis-webconf.sock" >> /etc/redis/redis.conf
      - /etc/init.d/redis-server start && sleep 3
      - redis-cli -p 6380 SET USER/testuser "testuser:x:12345:54321:Web User:/home/testuser:/bin/false"
      - redis-cli -p 6380 SET USER/12345 "testuser:x:12345:54321:Web User:/home/testuser:/bin/false"
      - redis-cli -p 6380 SET GROUP/testgroup "testgroup:x:54321:www-data"
      - redis-cli -p 6380 SET GROUP/54321 "testgroup:x:54321:www-data"
      - redis-cli -p 6380 SET WEBHOST/website.com "website.com:www.website.com:testuser:/home/testuser/public_html/www/:/var/run/mysqld/mysql.sock:default:display_errors=1;magic_quotes_gpc=1;"
      - scan-build make
      - scan-build make test
      - make
      - make test 
      - valgrind ./test

  testing-suffix:
    image: dock.pw.fr/pw/debpkg:${DEBIAN_VERSION}
    commands:
        - dch -l ~build`date +"%y%m%d%H%M"`deb`lsb_release -r -s | cut -d'.' -f1`u   `git rev-parse HEAD | cut -c1-8`
    when:
      event: push

  bundle:
    image: dock.pw.fr/pw/debpkg:${DEBIAN_VERSION}
    commands:
      - apt-get install -y libhiredis-dev
      - dpkg-buildpackage -b
      - fakeroot debian/rules clean

  pkg-testing:
    image: appleboy/drone-scp
    host: pippin.planet-work.net
    username: pkg
    source: ../*.deb
    target: incoming-testing/libnss-redis/${DEBIAN_VERSION}
    secrets: [ PLUGIN_KEY ]
    when:
      event: push

  aptly-testing:
    image: appleboy/drone-ssh
    host: pippin.planet-work.net
    username: pkg
    script:
      - aptly repo remove debian-${DEBIAN_VERSION}-testing `aptly repo search debian-${DEBIAN_VERSION}-testing 'Name (~ libnss-redis.*)' | xargs` || true
      - aptly repo add debian-${DEBIAN_VERSION}-testing incoming-testing/libnss-redis/${DEBIAN_VERSION} && aptly publish update ${DEBIAN_VERSION}-testing debian 
    secrets: [ PLUGIN_KEY ]
    when:
      event: push

  pkg:
    image: appleboy/drone-scp
    host: pippin.planet-work.net
    username: pkg
    source: ../*.deb
    target: incoming/libnss-redis/${DEBIAN_VERSION}
    secrets: [ PLUGIN_KEY ]
    when:
        event: tag


  aptly:
    image: appleboy/drone-ssh
    host: pippin.planet-work.net
    username: pkg
    script:
      - aptly repo add debian-${DEBIAN_VERSION} incoming/libnss-redis/${DEBIAN_VERSION} && aptly publish update ${DEBIAN_VERSION} debian 
    secrets: [ PLUGIN_KEY ]
    when:
      event: tag

  functional-tests:
    image: dock.pw.fr/pw/debpkg:${DEBIAN_VERSION}
    commands:
      - echo "deb http://ftp.fr.debian.org/debian/ ${DEBIAN_VERSION}-backports main" > /etc/apt/sources.list.d/backports.list
      - echo "deb [arch=amd64] http://pkg.planet-work.com/debian ${DEBIAN_VERSION}-testing main" > /etc/apt/sources.list.d/planet-work.list
      - apt-get update >/dev/null
      - '[ "${DEBIAN_VERSION}" = "stretch" ] && apt-get install -y redis-server || apt-get install -y -t ${DEBIAN_VERSION}-backports redis-server'
      - sed -i -e "s/6379/6380/" /etc/redis/redis.conf
      - echo "unixsocket /var/run/redis/redis-webconf.sock" >> /etc/redis/redis.conf
      - /etc/init.d/redis-server start && sleep 3
      - apt-get -y --allow-unauthenticated install libnss-redis
      - sed -i -e "s/compat/compat redis/g" /etc/nsswitch.conf
      - bash -x tests/setup-tests.sh
      - bash -x tests/run-tests.sh
    when:
      local: true

matrix:
  DEBIAN_VERSION:
    - wheezy
    - jessie
    - stretch

